export {default as ProductCard} from './product-card/ProductCard';
export {default as ComponentSlider} from './ComponentSlider';
export {default as WhyChooseUsItem} from './WhyChooseUsItem';
export {default as ResetPasswordComponent} from './ResetPasswordComponent';
export {default as RegisterComponent} from './RegisterComponent';
export {default as LoginComponent} from './LoginComponent';
export {default as ShoppingCartTitle} from './ShoppingCartTitle';
export {default as CartItem} from './CartItem';
export {default as InputForm} from './InputForm';
export {default as DeliveryMethodCard} from './DeliveryMethodCard';
export {default as DisabledPaymentChip} from './DisabledPaymentChip';
export {default as PagingIndicator} from './PagingIndicator';
export {default as CheckBox} from './CheckBox';
export {default as SizeButton} from './SizeButton';
export {default as ColorPallet} from './ColorPallet';
export {default as SizePallet} from './SizePallet';
export {default as PricePallet} from './PricePallet';
export {default as CategoryPallet} from './CategoryPallet';

